<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'BRIEFING envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'uminimo@hotmail.com',
		'to' => 'uminimo@hotmail.com'
	),
	'fields' => array(
		'custom_U509648' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome e sobrenome *',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome e sobrenome *\" é obrigatório.'
			)
		),
		'custom_U509677' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Nome da empresa *',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome da empresa *\" é obrigatório.'
			)
		),
		'custom_U511910' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ramo de atividade',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U512356' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Verba disponível para o projeto',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U512388' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Prazo de entrega',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U514352' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Contato *',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Contato *\" é obrigatório.'
			)
		),
		'custom_U518063' => array(
			'order' => 16,
			'type' => 'string',
			'label' => 'Alguma restrição sobre o projeto?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518149' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Quais produtos e/ou serviços oferece?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518177' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Perfil de consumidores',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518205' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Quem são os concorrentes?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518233' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Defina o diferencial da empresa',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518296' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Cores ou tipografia específica',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518352' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Tipo de formato ou material',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U518380' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Informações importantes a incluir',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U519595' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'O que precisa? *',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"O que precisa? *\" é obrigatório.'
			)
		),
		'custom_U519625' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Objetivo do projeto',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
